### ISSUE TITLE
Remove background image and update font

### ISSUE THREAD

**Issue by Aristarhys** [ChaikaBogdan/Hellspring#14]
Is menu background needed? If so, clearly new one must be themed right.
Also needed not so default looking font.

**Comment by ChaikaBogdan** [comment]
what do u mean but not so deafult? clearly we can adapt every font we want, cos font represented by png tileset. examples?

**Comment by Aristarhys** [comment]
Something more crispy
![incoshow](https://user-images.githubusercontent.com/5488514/30321094-850c2a60-97bd-11e7-9ecd-ccbc9e888939.png)

**Comment by Aristarhys** [comment]
@ChaikaBogdan you don't answer me about menu background image - my proposal  is to remove it completly leaving only font as asset for now.

**Comment by ChaikaBogdan** [comment]
@Aristarhys ok, remove it

**Comment by Aristarhys** [comment]
@ChaikaBogdan i will remove background image and update font then.

**Comment by ChaikaBogdan** [comment]
@Aristarhys if you have problems, try to change type layout and type rows count
