### ISSUE TITLE
Background music and sounds

### ISSUE THREAD

**Issue by Aristarhys** [ChaikaBogdan/Hellspring#15]
Do we need to add audio in the game? My opinion - no.

**Comment by ChaikaBogdan** [comment]
On one hand - for such first project, we may skip this feature.
On other hand - it will be dull, without it.
Libtcod does not support sound at all, so we need pygame or some pure sound lib to implement  sound&music

**Comment by ChaikaBogdan** [comment]
@Aristarhys okay lets skip it for now, and concentrate on gameplay

**Comment by Aristarhys** [comment]
@ChaikaBogdan sure
