### ISSUE TITLE
Increase screen size

### ISSUE THREAD

**Issue by Aristarhys** [ChaikaBogdan/Hellspring#16]
80 x 50 is a bit small, i think it needs to be scaled up.

**Comment by ChaikaBogdan** [comment]
We want one huge level? Well then  we will be forced to impement scroll, and show player some minimap
http://www.roguebasin.com/index.php?title=Complete_Roguelike_Tutorial,_using_python%2Blibtcod,_extras_scrolling_code

**Comment by ChaikaBogdan** [comment]
@Aristarhys  may we  delay this feature a little until we implement core?

**Comment by Aristarhys** [comment]
Yeah @ChaikaBogdan, agreed.
