### ISSUE TITLE
List of player statuses

### ISSUE THREAD

**Issue by ChaikaBogdan** [ChaikaBogdan/Hellspring#19]
We need create first revision of players statuses to show, before (and while) implementing https://github.com/ChaikaBogdan/Hellspring/issues/5 https://github.com/ChaikaBogdan/Hellspring/issues/6

We already have "melee lock" what else must be show in status? Low HP warning?

**Comment by Aristarhys** [comment]
@ChaikaBogdan we clearly must have any statuses "hacked", "uncontrollable", "burning" e.t.c. Make status system agile! Except "melee lock" core battle statuses must be "flanked", "exposured" (non covered, receving full damage for example by backstab.
